# Generated by Django 4.1.1 on 2022-09-14 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('zoom_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='UsersRooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participate', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignroom.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userRoom',
            },
        ),
        migrations.AddField(
            model_name='rooms',
            name='user',
            field=models.ManyToManyField(through='assignroom.UsersRooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
