# Generated by Django 4.1.1 on 2022-09-15 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignroom', '0002_alter_rooms_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='user',
            field=models.ManyToManyField(blank=True, through='assignroom.UsersRooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
